#include <stdint.h>


typedef void (*cmd_t)(uint32_t op, uint32_t diff); 

struct ge_cmd_t {
	uint8_t flags;
	uint64_t dirty;
	cmd_t func;	
} ge_cmd_table[255] = {
	// From Common. No flushing but definitely need execute.
	[SCE_GE_CMD_OFFSETADDR]  = { FLAG_EXECUTE, 0, &GPUCommon::Execute_OffsetAddr },
	[SCE_GE_CMD_ORIGIN]      = { FLAG_EXECUTE | FLAG_READS_PC, 0, &GPUCommon::Execute_Origin },
	[SCE_GE_CMD_JUMP]        = { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, &GPUCommon::Execute_Jump },
	[SCE_GE_CMD_CALL]        = { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, &GPUCommon::Execute_Call },
	[SCE_GE_CMD_RET]         = { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, &GPUCommon::Execute_Ret },
	[SCE_GE_CMD_END]         = { FLAG_FLUSHBEFORE | FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, &GPUCommon::Execute_End },
	[SCE_GE_CMD_VADDR]       = { FLAG_EXECUTE, 0, &GPUCommon::Execute_Vaddr },
	[SCE_GE_CMD_IADDR]       = { FLAG_EXECUTE, 0, &GPUCommon::Execute_Iaddr },
	[SCE_GE_CMD_BJUMP]       = { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, &GPUCommon::Execute_BJump },  // EXECUTE
	[SCE_GE_CMD_BOUNDINGBOX] = { FLAG_EXECUTE, 0, &GPUCommon::Execute_BoundingBox }, // + FLUSHBEFORE when we implement... or not, do we need to?

	[SCE_GE_CMD_PRIM]   = { FLAG_EXECUTE, 0, &GPUCommon::Execute_Prim },
	[SCE_GE_CMD_BEZIER] = { FLAG_FLUSHBEFORE | FLAG_EXECUTE, 0, &GPUCommon::Execute_Bezier },
	[SCE_GE_CMD_SPLINE] = { FLAG_FLUSHBEFORE | FLAG_EXECUTE, 0, &GPUCommon::Execute_Spline },

	// Changing the vertex type requires us to flush.
	[SCE_GE_CMD_VERTEXTYPE] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_VertexType },

	[SCE_GE_CMD_LOADCLUT] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTE, 0, &GPUCommon::Execute_LoadClut },

	// These two are actually processed in CMD_END. Not sure if FLAG_FLUSHBEFORE matters.
	[SCE_GE_CMD_SIGNAL] = { FLAG_FLUSHBEFORE, 0, NULL },
	[SCE_GE_CMD_FINISH] = { FLAG_FLUSHBEFORE, 0, NULL },

	// Changes that dirty the framebuffer
	[SCE_GE_CMD_FRAMEBUFPTR]       = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_FRAMEBUFWIDTH]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },
	[SCE_GE_CMD_FRAMEBUFPIXFORMAT] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_BLEND_STATE | DIRTY_DEPTHSTENCIL_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_ZBUFPTR]           = { FLAG_FLUSHBEFOREONCHANGE, 0, NULL },
	[SCE_GE_CMD_ZBUFWIDTH]         = { FLAG_FLUSHBEFOREONCHANGE, 0, NULL },

	[SCE_GE_CMD_FOGCOLOR]          = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FOGCOLOR, NULL },
	[SCE_GE_CMD_FOG1]              = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FOGCOEF, NULL },
	[SCE_GE_CMD_FOG2]              = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FOGCOEF, NULL },

	// These affect the fragment shader so need flushing.
	[SCE_GE_CMD_CLEARMODE]        = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_DEPTHSTENCIL_STATE | DIRTY_RASTER_STATE | DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE | DIRTY_VERTEXSHADER_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_TEXTUREMAPENABLE] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_FOGENABLE]        = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_TEXMODE]          = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_TEXSHADELS]       = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE, NULL },
	// Raster state for Direct3D 9, uncommon.
	[SCE_GE_CMD_SHADEMODE]       = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_FRAGMENTSHADER_STATE | DIRTY_RASTER_STATE, NULL },
	[SCE_GE_CMD_TEXFUNC]         = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_COLORTEST]       = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_ALPHATESTENABLE] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_COLORTESTENABLE] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_COLORTESTMASK]   = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_ALPHACOLORMASK | DIRTY_FRAGMENTSHADER_STATE, NULL },

	// These change the vertex shader so need flushing.
	[SCE_GE_CMD_REVERSENORMAL]  = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE, NULL },
	[SCE_GE_CMD_LIGHTINGENABLE] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_LIGHTENABLE0]   = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE, NULL  },
	[SCE_GE_CMD_LIGHTENABLE1]   = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE, NULL  },
	[SCE_GE_CMD_LIGHTENABLE2]   = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE, NULL  },
	[SCE_GE_CMD_LIGHTENABLE3]   = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE, NULL  },
	[SCE_GE_CMD_LIGHTTYPE0]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LIGHTTYPE1]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LIGHTTYPE2]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LIGHTTYPE3]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_MATERIALUPDATE] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },

	// These change both shaders so need flushing.
	[SCE_GE_CMD_LIGHTMODE] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },

	[SCE_GE_CMD_TEXFILTER] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXWRAP]   = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS | DIRTY_FRAGMENTSHADER_STATE, NULL },

	// Uniform changes. though the fragmentshader optimizes based on these sometimes.
	[SCE_GE_CMD_ALPHATEST]   = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_ALPHACOLORREF | DIRTY_ALPHACOLORMASK | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_COLORREF]    = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_ALPHACOLORREF | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_TEXENVCOLOR] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXENV, NULL },

	// Simple render state changes. Handled in StateMapping.cpp.
	[SCE_GE_CMD_CULL]              = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_RASTER_STATE, NULL },
	[SCE_GE_CMD_CULLFACEENABLE,]   = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_RASTER_STATE, NULL },
	[SCE_GE_CMD_DITHERENABLE]      = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_RASTER_STATE, NULL },
	[SCE_GE_CMD_STENCILOP]         = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_DEPTHSTENCIL_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_STENCILTEST]       = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_STENCILREPLACEVALUE | DIRTY_BLEND_STATE | DIRTY_DEPTHSTENCIL_STATE, NULL },
	[SCE_GE_CMD_STENCILTESTENABLE] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_DEPTHSTENCIL_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_ALPHABLENDENABLE]  = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_BLENDMODE]         = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_BLENDFIXEDA]       = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_BLENDFIXEDB]       = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_MASKRGB]           = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_MASKALPHA]         = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_FRAGMENTSHADER_STATE | DIRTY_DEPTHSTENCIL_STATE, NULL },
	[SCE_GE_CMD_ZTEST]             = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_DEPTHSTENCIL_STATE, NULL },
	[SCE_GE_CMD_ZTESTENABLE]       = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_DEPTHSTENCIL_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_ZWRITEDISABLE]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_DEPTHSTENCIL_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_LOGICOP]           = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },
	[SCE_GE_CMD_LOGICOPENABLE]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_BLEND_STATE | DIRTY_FRAGMENTSHADER_STATE, NULL },

	[SCE_GE_CMD_TEXMAPMODE] = { , FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE | DIRTY_FRAGMENTSHADER_STATE },

	// These are read on every SubmitPrim, no need for dirtying or flushing.
	[SCE_GE_CMD_TEXSCALEU] = { 0, 0, NULL},
	[SCE_GE_CMD_TEXSCALEV] = { 0, 0, NULL},
	[SCE_GE_CMD_TEXOFFSETU] = { 0, 0, NULL},
	[SCE_GE_CMD_TEXOFFSETV] = { 0, 0, NULL},

	[SCE_GE_CMD_TEXSIZE0]     = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTE, 0, &GPUCommon::Execute_TexSize0 },
	[SCE_GE_CMD_TEXSIZE1]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXSIZE2]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXSIZE3]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXSIZE4]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXSIZE5]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXSIZE6]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXSIZE7]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXFORMAT]    = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_IMAGE, NULL },
	[SCE_GE_CMD_TEXLEVEL]     = { FLAG_EXECUTEONCHANGE,     DIRTY_TEXTURE_PARAMS, &GPUCommon::Execute_TexLevel },
	[SCE_GE_CMD_TEXLODSLOPE]  = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXADDR0]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_IMAGE | DIRTY_UVSCALEOFFSET, NULL },
	[SCE_GE_CMD_TEXADDR1]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXADDR2]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXADDR3]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXADDR4]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXADDR5]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXADDR6]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXADDR7]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXBUFWIDTH0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_IMAGE, NULL },
	[SCE_GE_CMD_TEXBUFWIDTH1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXBUFWIDTH2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXBUFWIDTH3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXBUFWIDTH4] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXBUFWIDTH5] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXBUFWIDTH6] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },
	[SCE_GE_CMD_TEXBUFWIDTH7] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS, NULL },

	// These must flush on change, so that LoadClut doesn't have to always flush.
	[SCE_GE_CMD_CLUTADDR]      = { FLAG_FLUSHBEFOREONCHANGE, 0, NULL },
	[SCE_GE_CMD_CLUTADDRUPPER] = { FLAG_FLUSHBEFOREONCHANGE, 0, NULL },
	[SCE_GE_CMD_CLUTFORMAT]    = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_TEXTURE_PARAMS | DIRTY_DEPAL, NULL },

	// Morph weights. TODO: Remove precomputation?
	[SCE_GE_CMD_MORPHWEIGHT0] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_MorphWeight },
	[SCE_GE_CMD_MORPHWEIGHT1] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_MorphWeight },
	[SCE_GE_CMD_MORPHWEIGHT2] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_MorphWeight },
	[SCE_GE_CMD_MORPHWEIGHT3] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_MorphWeight },
	[SCE_GE_CMD_MORPHWEIGHT4] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_MorphWeight },
	[SCE_GE_CMD_MORPHWEIGHT5] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_MorphWeight },
	[SCE_GE_CMD_MORPHWEIGHT6] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_MorphWeight },
	[SCE_GE_CMD_MORPHWEIGHT7] = { FLAG_FLUSHBEFOREONCHANGE | FLAG_EXECUTEONCHANGE, 0, &GPUCommon::Execute_MorphWeight },

	// Control spline/bezier patches. Don't really require flushing as such, but meh.
	[SCE_GE_CMD_PATCHDIVISION]   = { FLAG_FLUSHBEFOREONCHANGE, 0, NULL },
	[SCE_GE_CMD_PATCHPRIMITIVE]  = { FLAG_FLUSHBEFOREONCHANGE, 0, NULL },
	[SCE_GE_CMD_PATCHFACING]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VERTEXSHADER_STATE, NULL },
	[SCE_GE_CMD_PATCHCULLENABLE] = { FLAG_FLUSHBEFOREONCHANGE, 0, NULL },

	// Can probably ignore this one as we don't support AA lines.
	[SCE_GE_CMD_ANTIALIASENABLE] = { FLAG_FLUSHBEFOREONCHANGE, 0, NULL },

	// Viewport.
	[SCE_GE_CMD_OFFSETX]          = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },
	[SCE_GE_CMD_OFFSETY]          = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },
	[SCE_GE_CMD_VIEWPORTXSCALE]   = { FLAG_FLUSHBEFOREONCHANGE,  DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_CULLRANGE | DIRTY_PROJMATRIX | DIRTY_VIEWPORTSCISSOR_STATE, NULL },
	[SCE_GE_CMD_VIEWPORTYSCALE]   = { FLAG_FLUSHBEFOREONCHANGE,  DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_CULLRANGE | DIRTY_PROJMATRIX | DIRTY_VIEWPORTSCISSOR_STATE, NULL },
	[SCE_GE_CMD_VIEWPORTXCENTER]  = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_CULLRANGE | DIRTY_PROJMATRIX | DIRTY_VIEWPORTSCISSOR_STATE, NULL },
	[SCE_GE_CMD_VIEWPORTYCENTER]  = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_CULLRANGE | DIRTY_PROJMATRIX | DIRTY_VIEWPORTSCISSOR_STATE, NULL },
	[SCE_GE_CMD_VIEWPORTZSCALE]   = { FLAG_FLUSHBEFOREONCHANGE,  DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_CULLRANGE | DIRTY_DEPTHRANGE | DIRTY_PROJMATRIX | DIRTY_VIEWPORTSCISSOR_STATE, NULL },
	[SCE_GE_CMD_VIEWPORTZCENTER]  = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_CULLRANGE | DIRTY_DEPTHRANGE | DIRTY_PROJMATRIX | DIRTY_VIEWPORTSCISSOR_STATE, NULL },
	[SCE_GE_CMD_DEPTHCLAMPENABLE] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE | DIRTY_RASTER_STATE, NULL },

	// Z clip
	[SCE_GE_CMD_MINZ] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_DEPTHRANGE | DIRTY_RASTER_STATE | DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },
	[SCE_GE_CMD_MAXZ] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_DEPTHRANGE | DIRTY_RASTER_STATE | DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },

	// Region
	[SCE_GE_CMD_REGION1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },
	[SCE_GE_CMD_REGION2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },

	// Scissor
	[SCE_GE_CMD_SCISSOR1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },
	[SCE_GE_CMD_SCISSOR2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_FRAMEBUF | DIRTY_TEXTURE_PARAMS | DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_CULLRANGE, NULL },

	// Lighting base colors
	[SCE_GE_CMD_AMBIENTCOLOR]         = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_AMBIENT, NULL },
	[SCE_GE_CMD_AMBIENTALPHA]         = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_AMBIENT, NULL },
	[SCE_GE_CMD_MATERIALDIFFUSE]      = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_MATDIFFUSE, NULL },
	[SCE_GE_CMD_MATERIALEMISSIVE]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_MATEMISSIVE, NULL },
	[SCE_GE_CMD_MATERIALAMBIENT]      = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_MATAMBIENTALPHA, NULL },
	[SCE_GE_CMD_MATERIALALPHA]        = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_MATAMBIENTALPHA, NULL },
	[SCE_GE_CMD_MATERIALSPECULAR]     = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_MATSPECULAR, NULL },
	[SCE_GE_CMD_MATERIALSPECULARCOEF] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_MATSPECULAR, NULL },

	// Light parameters
	[SCE_GE_CMD_LX0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LY0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LZ0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LX1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LY1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LZ1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LX2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LY2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LZ2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LX3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_LY3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_LZ3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },

	[SCE_GE_CMD_LDX0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LDY0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LDZ0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LDX1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LDY1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LDZ1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LDX2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LDY2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LDZ2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LDX3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_LDY3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_LDZ3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },

	[SCE_GE_CMD_LKA0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LKB0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LKC0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LKA1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LKB1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LKC1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LKA2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LKB2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LKC2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LKA3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_LKB3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_LKC3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },

	[SCE_GE_CMD_LKS0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LKS1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LKS2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LKS3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },

	[SCE_GE_CMD_LKO0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LKO1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LKO2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LKO3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },

	[SCE_GE_CMD_LAC0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LDC0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LSC0] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT0, NULL },
	[SCE_GE_CMD_LAC1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LDC1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LSC1] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT1, NULL },
	[SCE_GE_CMD_LAC2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LDC2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LSC2] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT2, NULL },
	[SCE_GE_CMD_LAC3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_LDC3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },
	[SCE_GE_CMD_LSC3] = { FLAG_FLUSHBEFOREONCHANGE, DIRTY_LIGHT3, NULL },

	// Ignored commands
	[SCE_GE_CMD_TEXFLUSH] = {  },
	[SCE_GE_CMD_TEXSYNC] = {  },

	// These are just nop or part of other later commands.
	[SCE_GE_CMD_NOP] = {  },
	[SCE_GE_CMD_BASE] = {  },
	[SCE_GE_CMD_TRANSFERSRC] = {  },
	[SCE_GE_CMD_TRANSFERSRCW] = {  },
	[SCE_GE_CMD_TRANSFERDST] = {  },
	[SCE_GE_CMD_TRANSFERDSTW] = { 0, 0, NULL },
	[SCE_GE_CMD_TRANSFERSRCPOS] = { 0, 0, NULL },
	[SCE_GE_CMD_TRANSFERDSTPOS] = { 0, 0, NULL },
	[SCE_GE_CMD_TRANSFERSIZE] = { 0, 0, NULL },
	[SCE_GE_CMD_TRANSFERSTART] = { , FLAG_FLUSHBEFORE | FLAG_EXECUTE | FLAG_READS_PC, 0, &GPUCommon::Execute_BlockTransferStart },

	// We don't use the dither table.
	[SCE_GE_CMD_DITH0] = { 0, 0, NULL},
	[SCE_GE_CMD_DITH1] = { 0, 0, NULL},
	[SCE_GE_CMD_DITH2] = { 0, 0, NULL},
	[SCE_GE_CMD_DITH3] = { 0, 0, NULL},

	// These handle their own flushing.
	[SCE_GE_CMD_WORLDMATRIXNUMBER] = { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, ge_cmd_mtx_world_num },
	[SCE_GE_CMD_WORLDMATRIXDATA] =   { FLAG_EXECUTE,                                  0, ge_cmd_mtx_world_data },
	[SCE_GE_CMD_VIEWMATRIXNUMBER] =  { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, ge_cmd_mtx_view_num },
	[SCE_GE_CMD_VIEWMATRIXDATA] =    { FLAG_EXECUTE,                                  0, ge_cmd_mtx_view_data },
	[SCE_GE_CMD_PROJMATRIXNUMBER] =  { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, ge_cmd_mtx_proj_num },
	[SCE_GE_CMD_PROJMATRIXDATA] =    { FLAG_EXECUTE,                                  0, ge_cmd_mtx_proj_data },
	[SCE_GE_CMD_TGENMATRIXNUMBER] =  { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, ge_cmd_mtx_tgen_num },
	[SCE_GE_CMD_TGENMATRIXDATA] =    { FLAG_EXECUTE,                                  0, ge_cmd_mtx_tgen_data },
	[SCE_GE_CMD_BONEMATRIXNUMBER] =  { FLAG_EXECUTE | FLAG_READS_PC | FLAG_WRITES_PC, 0, ge_cmd_mtx_bone_num },
	[SCE_GE_CMD_BONEMATRIXDATA] =    { FLAG_EXECUTE,                                  0, ge_cmd_mtx_bone_data },

	// Vertex Screen/Texture/Color
	[SCE_GE_CMD_VSCX] = { 0, 0, NULL},
	[SCE_GE_CMD_VSCY] = { 0, 0, NULL},
	[SCE_GE_CMD_VSCZ] = { 0, 0, NULL},
	[SCE_GE_CMD_VTCS] = { 0, 0, NULL},
	[SCE_GE_CMD_VTCT] = { 0, 0, NULL},
	[SCE_GE_CMD_VTCQ] = { 0, 0, NULL},
	[SCE_GE_CMD_VCV]  = { 0, 0, NULL },
	[SCE_GE_CMD_VAP]  = { FLAG_EXECUTE, 0, &GPUCommon::Execute_ImmVertexAlphaPrim },
	[SCE_GE_CMD_VFC]  = { 0, 0, NULL},
	[SCE_GE_CMD_VSCV] = { 0, 0, NULL},

	// "Missing" commands (gaps in the sequence)
	[SCE_GE_CMD_UNKNOWN_03] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_0D] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_11] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_29] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_34] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_35] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_39] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_4E] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_4F] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_52] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_59] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_5A] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_B6] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_B7] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_D1] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_ED] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_EF] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_FA] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_FB] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_FC] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_FD] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	[SCE_GE_CMD_UNKNOWN_FE] = { FLAG_EXECUTE, 0, ge_cmd_unk },
	// Appears to be debugging related or something?  Hit a lot in GoW.
	[SCE_GE_CMD_NOP_FF] = { 0, 0, NULL },
};

static void ge_cmd_unk(uint32_t op, uint32_t diff)
{
	// TODO: log warning
}

static void ge_cmd_mtx_tgen_num(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_tgen_data(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_view_num(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_view_data(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_world_num(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_world_data(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_bone_num(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_bone_data(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_proj_num(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_mtx_proj_data(uint32_t op, uint32_t diff)
{
}

static void ge_cmd_morph_weight(uint32_t op, uint32_t diff)
{
	gstate_c.morphWeights[(op >> 24) - GE_CMD_MORPHWEIGHT0] = getFloat24(op);
}
Execute_Bezier
Execute_BJump
Execute_BlockTransferStart
Execute_BoundingBox
Execute_Call
Execute_End
Execute_Iaddr
Execute_ImmVertexAlphaPrim
Execute_Jump
Execute_LoadClut
Execute_MorphWeight
Execute_OffsetAddr
Execute_Origin
Execute_Prim
Execute_Ret
Execute_Spline
Execute_TexLevel
Execute_TexSize0
Execute_Vaddr
Execute_VertexType
